"""update user model

Revision ID: 7f0c086ec3d5
Revises: e3f5753f1be2
Create Date: 2025-05-01 15:22:26.090108

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7f0c086ec3d5'
down_revision: Union[str, None] = 'e3f5753f1be2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('holdings', 'portfolio_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('holdings', 'symbol',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('holdings', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('holdings', 'shares',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('holdings', 'value',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('holdings', 'allocation',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('holdings', 'last_updated',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('portfolios', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('portfolios', 'total_value',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('portfolios', 'last_updated',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('user_settings', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('user_settings', 'notifications_enabled',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('user_settings', 'email_updates_enabled',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('user_settings', 'dark_mode_enabled',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.add_column('users', sa.Column('full_name', sa.String(), nullable=True))
    op.add_column('users', sa.Column('is_superuser', sa.Boolean(), nullable=True))
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('users', 'hashed_password',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('users', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.drop_constraint('users_email_key', 'users', type_='unique')
    op.drop_column('users', 'name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.create_unique_constraint('users_email_key', 'users', ['email'])
    op.alter_column('users', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('users', 'hashed_password',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('users', 'is_superuser')
    op.drop_column('users', 'full_name')
    op.alter_column('user_settings', 'dark_mode_enabled',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('user_settings', 'email_updates_enabled',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('user_settings', 'notifications_enabled',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('user_settings', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('portfolios', 'last_updated',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('portfolios', 'total_value',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('portfolios', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('holdings', 'last_updated',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('holdings', 'allocation',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('holdings', 'value',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('holdings', 'shares',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('holdings', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('holdings', 'symbol',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('holdings', 'portfolio_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
